[agent]
  interval = "5s"
  flush_interval = "10s"
  debug = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://lima-mqtt:1883"]
  topics = ["lima/#"]
  qos = 0
  connection_timeout = "30s"
  
  name_override = "lima_metrics"
  
  data_format = "json"
  json_time_key = "ts"
  json_time_format = "2006-01-02T15:04:05.999999999"
  
  tag_keys = ["cmd", "status"]
  json_string_fields = ["cmd", "status"]

[[outputs.influxdb_v2]]
  urls = ["http://lima-influxdb:8086"]
  token = "lima-secret-token-2024"
  organization = "lima_org"
  bucket = "lima_data"